/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { LoginRequestBuilderRequestsMetadata, type LoginRequestBuilder } from './login/index.js';
// @ts-ignore
import { Refresh_tokenRequestBuilderRequestsMetadata, type Refresh_tokenRequestBuilder } from './refresh_token/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/account
 */
export interface AccountRequestBuilder extends BaseRequestBuilder<AccountRequestBuilder> {
    /**
     * The login property
     */
    get login(): LoginRequestBuilder;
    /**
     * The refresh_token property
     */
    get refresh_token(): Refresh_tokenRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AccountRequestBuilderUriTemplate = "{+baseurl}/api/account";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AccountRequestBuilderNavigationMetadata: Record<Exclude<keyof AccountRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    login: {
        requestsMetadata: LoginRequestBuilderRequestsMetadata,
    },
    refresh_token: {
        requestsMetadata: Refresh_tokenRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
